### ISSUE TITLE
Certain settings not applying.

### ISSUE THREAD

**Issue by Pommaq** [nick92/Enso-OS#30] opened 2018-08-20 15:48 UTC
As the title says. Certain settings doesn't apply when checked.

So far these are the things I've found that doesn't apply when chosen:
* changing wallpaper. - Dock and launcher settings apply just fine.
* Notification settings.
* Workspace settings.

I can make the wallpaper apply by logging in and out, or changing my display settings (like choosing another primary screen.), or opening my laptop lid (I have it connected to a secondary screen.).
The rest doesn't seem to apply. ever.

**Comment by EasyDevCpp** [comment] 2018-08-20 16:34
I guess this is due to the fact that the wallpaper is set for xfce but is drawn by the Pantheon fork or Inverted. This may applys for the other settings too... The solution might be usage of the xfce confs instead of the Pantheon native confs.

**Comment by EasyDevCpp** [comment] 2018-08-21 07:40
What does this file "~/.config/xfce4/mcs_settings/desktop.xml" say?
Does the option "<option name="imagepath_0_0" type="string" value="your_path"/>" represent your set wallpaper or the one you wanted to be set?

**Comment by nick92** [comment] 2018-08-21 11:01
It doesn't look like this setting gets changed if xfdekstop isn't running, may be a xconf event that we can listen to in Gala to get this changed value

**Comment by nick92** [comment] 2018-08-21 12:12
with reg. to changing wallpaper - are you using a VM? this is an issue that I need to look into, works fine if the screen size doesn't change but fails as VM doesn't have a set size and can change on load - as mentioned logging out and in sometimes solves this problem

**Comment by nick92** [comment] 2018-08-21 13:33
Ok, will have a look at trying to reproduce this issue and see if I can see what the problem is

**Comment by nick92** [comment] 2018-08-21 14:55
> - Notification settings.
> - Workspace settings.

Will remove these settings from the menu as aren't required

**Comment by Pommaq** [comment] 2018-09-08 18:54
Just noticed wallpapers not applying seems to be random. Not sure if its function gets decided when booting the computer or not. Sometimes it works just fine, other times it doesn't.

**Comment by nick92** [comment] 2019-06-24 12:03
Will raise final point as separate bug and close this off as original problem is resolved

**Closed by nick92** 2019-06-24 12:03 UTC
Labels: bug
